### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by hmazer** [luximetr/AnyFormatKit#13]
If a TextField has textContentType set, autofill options will appear on the keyboard.
Tapping those options does nothing when using TextInputField.

**Comment by jvanzummeren** [comment]
Should be working in version 0.1.5

What is usecase of auto-formatting Textfield with autocomplete?

Closing the issue for now, if the problem still exists, please make a new issue

**Comment by hmazer** [comment]
Well, some users might have the autocomplete option, some others don’t. That’s why it’s important to support both.

Alright, I’ll test later and open a new one if necessary.
