### ISSUE TITLE
Swift 4.2?

### ISSUE THREAD

**Issue by ReveelTeam** [luximetr/AnyFormatKit#14]
Any plans to update for Swift 4.2? and if so how soon?

Have a running project that can't get to compile with Swift 4.2.

If I update all the new replacements wanted for 4.2, it is stuck on 2 places (textView's & textField's input overrides). Basically, the Swift-Language changes wanted to change [rename]: 'NSAttributedStringKey' to 'NSAttributedString.Key'. Which then (ultimately) creates these 2 issues:

1) Property 'defaultTextAttributes' with type '[String : Any]' cannot override a property with type '[NSAttributedString.Key : Any]' -- FOR: TextField

2) Property 'typingAttributes' with type '[String : Any]' cannot override a property with type '[NSAttributedString.Key : Any]' -- FOR: TextView

These need to get a property Type change since now the compiler doesn't like it.

**Comment by myanalysis** [comment]
Same here, though I got 4 errors.

I got a  few "Ambiguous use of 'typingAttributes" errors on top of the ones above.

thanks.

**Comment by jvanzummeren** [comment]
Version 0.1.3 now contains Swift 4.2 support
