### ISSUE TITLE
Release 0.1.3

### ISSUE THREAD

**Issue by jvanzummeren** [luximetr/AnyFormatKit#18]
Hi @luximetr,

Was great that you could merge those pull requests so quickly but i think there is still a release missing. I understand that maintaining a Cocoapod / Github can take up time and you're probably busy on different projects. I don't mind helping you out a bit if you give me some access rights on Github and Cocoapods so i can assist in maintaining it. 

I'm also actively maintaining [Markymark](https://github.com/M2Mobi/Marky-Mark), as a reference. 

Let me know what you think,

Kind regards,

Jim van Zummeren
M2mobi

**Comment by luximetr** [comment]
Nice idea. What should I do?

**Comment by jvanzummeren** [comment]
Great!

The steps would be i think to first add me as a collabarator with write access in settings:
<https://github.com/luximetr/AnyFormatKit/settings>

Second part would be to allow access on the Cocoapods trunk, this can be done when i try to push to the trunk and you will receive an e-mail to add me as contributor there.

I suggest i'd make the 0.1.3 release so we know we've got everything up and running :)

Thanks!

Kind regards,

**Comment by luximetr** [comment]
Take invite link:
https://github.com/luximetr/AnyFormatKit/invitations

**Comment by jvanzummeren** [comment]
Thanks! The invitation worked. I was able to update the podspec and draft a release.

Can you add me as owner on cocoapods? This should work i believe:

$ pod trunk add-owner AnyFormatKit j.van.zummeren@gmail.com

**Comment by luximetr** [comment]
Yes, it works. You are owner now.

**Comment by jvanzummeren** [comment]
Just released AnyFormatKit 0.1.3 on Cocoapods and Github!
Looking forward to keep improving this library and keeping it up to date together.

Thanks

**Comment by luximetr** [comment]
Thanks for help and your enthusiasm!
