### ISSUE TITLE
how change group separator to whitespace 

### ISSUE THREAD

**Issue by sereja93** [luximetr/AnyFormatKit#28]
when i set ` let sumFormatter = SumTextInputFormatter(textPattern: "# ###,## ₽")` cursor position wrong when delete text.  `let sumFormatter = SumTextInputFormatter(textPattern: "#.###,## ₽")` delete work fine

**Comment by luximetr** [comment]
That issue fixed. Version '2.0.1'. Please check. If it will reproduce, that open this issue again. Thank you.
