### ISSUE TITLE
Why iOS9 is not supported? :'(

### ISSUE THREAD

**Issue by MihaelIsaev** [luximetr/AnyFormatKit#33]
Tried to use it in my project which is iOS9.3+ and see error
`Compiling for iOS 9.3, but module 'AnyFormatKit' has a minimum deployment target of iOS 10.0`
That's sad..

**Comment by luximetr** [comment]
> Tried to use it in my project which is iOS9.3+ and see error
> `Compiling for iOS 9.3, but module 'AnyFormatKit' has a minimum deployment target of iOS 10.0`
> That's sad..

Noted. 
Minimum iOS version has been updated to 8.0 at AnyFormatKit v2.0.3.

**Comment by MihaelIsaev** [comment]
@luximetr thank you very much, that was fast! 🚀🥳 Could it be changed to iOS8 in `Package.swift` as well?

**Comment by luximetr** [comment]
> @luximetr thank you very much, that was fast! 🚀🥳 Could it be changed to iOS8 in `Package.swift` as well?

Okay, please check, should be available at SPM from version 2.0.6
