### ISSUE TITLE
Removed from DefaultTextInputFormatter unformat method ? 

### ISSUE THREAD

**Issue by juanxme** [luximetr/AnyFormatKit#34]
with 2.0.6, It works!
2.1.0, fails

**Comment by luximetr** [comment]
> with 2.0.6, It works!
> 2.1.0, fails

Yes, for DefaultTextInputFormatter `unformat` method was removed. 
From my perspective it was logically wrong to keep it in that class. 
To use `unformat` method you should use DefaultTextFormatter.
Let me know how to do it better and more convenient to use.
