### ISSUE TITLE
Exposing maximumIntegerCharacters in SumTextInputFormatter

### ISSUE THREAD

**Issue by wsalim1610** [luximetr/AnyFormatKit#36]
Hi,

In the version `2.0.1` that I previously used, we can change the `maximumIntegerCharacters` from `SumTextInputFormatter`. Previously it is possible since `SumTextInputFormatter` is inherited from `SumTextFormatter`, and `maximumIntegerCharacters` is declared public in `SumTextFormatter`.

On the current version (`2.2.1`) this is not the case anymore. Now `SumTextInputFormatter` are composed from `SumTextFormatter` and the instance of it (`textFormatter`) is declared as private. Now we have no way to change `maximumIntegerCharacters` if what we use is `SumTextInputFormatter`. Changing `maximumIntegerDigits` of its `numberFormatter` won't affect it.

I hope this can be added (or maybe give us another way to change it)

**Comment by luximetr** [comment]
Thank you for your message, sure, will take a look at it.

**Comment by luximetr** [comment]
> Hi,
> 
> In the version `2.0.1` that I previously used, we can change the `maximumIntegerCharacters` from `SumTextInputFormatter`. Previously it is possible since `SumTextInputFormatter` is inherited from `SumTextFormatter`, and `maximumIntegerCharacters` is declared public in `SumTextFormatter`.
> 
> On the current version (`2.2.1`) this is not the case anymore. Now `SumTextInputFormatter` are composed from `SumTextFormatter` and the instance of it (`textFormatter`) is declared as private. Now we have no way to change `maximumIntegerCharacters` if what we use is `SumTextInputFormatter`. Changing `maximumIntegerDigits` of its `numberFormatter` won't affect it.
> 
> I hope this can be added (or maybe give us another way to change it)

Should be fixed in version `2.3.0`. Please verify.

**Comment by wsalim1610** [comment]
Thanks a lot. it's working fine now
