### ISSUE TITLE
Xcode 14 bitcode

### ISSUE THREAD

**Issue by MarekSlaninka** [luximetr/AnyFormatKit#45]
Hi, in Beta Xcode 14 there is an error when building application. 
Is it possible to enable bitcode, or is there any other problem?
`error build: '/Users/marekslaninka/Library/Developer/Xcode/DerivedData/Surglogs-blzrfqsijprnfacgxqyzrxxylqzd/Build/Products/Debug-iphoneos/AnyFormatKit.o' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/marekslaninka/Library/Developer/Xcode/DerivedData/Surglogs-blzrfqsijprnfacgxqyzrxxylqzd/Build/Products/Debug-iphoneos/AnyFormatKit.o' for architecture arm64
`

**Comment by luximetr** [comment]
> Hi, in Beta Xcode 14 there is an error when building application.
> Is it possible to enable bitcode, or is there any other problem?
> `error build: '/Users/marekslaninka/Library/Developer/Xcode/DerivedData/Surglogs-blzrfqsijprnfacgxqyzrxxylqzd/Build/Products/Debug-iphoneos/AnyFormatKit.o' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/marekslaninka/Library/Developer/Xcode/DerivedData/Surglogs-blzrfqsijprnfacgxqyzrxxylqzd/Build/Products/Debug-iphoneos/AnyFormatKit.o' for architecture arm64`

Hello, as I understand bitcode is deprecated, maybe you need to disable for your project?
Please refer to 
 https://developer.apple.com/forums/thread/707443
https://stackoverflow.com/questions/41872838/libparselib-a-does-not-contain-bitcode-error/47300692#47300692

**Comment by MarekSlaninka** [comment]
Thank You for quick response. I was not aware of this.
