### ISSUE TITLE
Can I use this TextController/TextInputFormatter with TextInputField set in storyboard?

### ISSUE THREAD

**Issue by michzio** [luximetr/AnyFormatKit#5]
I have tried to use this library in my project. I have added such code in ViewController: 

```
 let textInputController1 = TextInputController()
        textInputController1.formatter = TextInputFormatter(textPattern: "(###) ###-####")
        textInputController1.textInput = mobilePhoneTextField
```

And then I have added TextInputField custom class in Identity Inspector of mobilePhoneTextField (here it is IBOutlet with type TextInputField) 

But live formatting doesn't work.

**Comment by Urkman** [comment]
Any news/help on this?

**Comment by thiagodelmotte** [comment]
+1

**Comment by luximetr** [comment]
Please, update to 1.0.0 version.
