### ISSUE TITLE
Cannot Implement TextInput protocol

### ISSUE THREAD

**Issue by cmillani** [luximetr/AnyFormatKit#6]
Due to a lack of an accessible init on MulticastDelegate class there is no way to create a class implementing the TextInput protocol. 

When trying to instantiate a MulticastDelegate, I get the following error:

`'MulticastDelegate<T>' initializer is inaccessible due to 'internal' protection level`

**Comment by jvanzummeren** [comment]
Fixed in version 0.1.4
