### ISSUE TITLE
How to initialize MulticastDelegate in my own UITextField class?

### ISSUE THREAD

**Issue by emreond** [luximetr/AnyFormatKit#9]
When I add TextInput protocol into my own UITextField class and It wants me to initialize MulticastDelegate but I don't know how. I tried MulticastDelegate<TextInputDelegate>() but It gives "'MulticastDelegate<T>' initializer is inaccessible due to 'internal' protection level" error.

**Comment by jvanzummeren** [comment]
Fixed in version 0.1.4
